name: Cleanup Docker Hub Tags

on: workflow_dispatch

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cleanup Docker Hub tags
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          # Keep only last 5 tags for each repository
          docker run --rm lumir/remove-dockerhub-tag \
            --user $DOCKER_USERNAME \
            --password $DOCKER_PASSWORD \
            --keep 5 \
            $DOCKER_USERNAME/mern-realty-client
