name: Release API

on:
  workflow_run:
    workflows: ["Testing Pipeline"]
    types:
      - completed

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files_yaml: |
            api:
              - api/**
              - package.json
              - package-lock.json
              - .releaserc.json
              - Dockerfile
              - .dockerignore
              - .babelrc
              - jest.config.js
              - jest.setup.js

      - name: Check if any files were changed
        if: steps.changed-files.outputs.api_any_changed == 'true'
        run: npm ci

      - name: Semantic release (API)
        if: steps.changed-files.outputs.api_any_changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
